# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

Vagrant.configure(2) do |config|
  # Give it a name
  config.vm.hostname = "docker-host"
  
  #disable local file synch
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false
  
  # LTS 14.04
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.box_check_update = false
  
  # Provision with docker
  config.vm.provision "docker"
end
